[build]
builder = "DOCKERFILE"
dockerfilePath = "sales_service/Dockerfile"

[deploy]
startCommand = "sh -c 'alembic -c migrations/alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT'"
healthcheckPath = "/sales/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
